ADATA = $(foreach dir,data/src/data,$(notdir $(wildcard $(dir)/*.s)))
CDATA = $(foreach dir,data/src/data,$(notdir $(wildcard $(dir)/*.c)))
MDATA = $(foreach dir,data/src/data/music,$(notdir $(wildcard $(dir)/*.c)))
SDATA = $(foreach dir,data/src/data/sounds,$(notdir $(wildcard $(dir)/*.c)))

OBJS = $(filter-out $(TOP)$(OBJDIR)/main.o, $(ENGINE_OBJS)) \
	$(ADATA:%.s=$(OBJDIR)/%.o) \
	$(CDATA:%.c=$(OBJDIR)/%.o) \
	$(MDATA:%.c=$(OBJDIR)/%.o) \
	$(SDATA:%.c=$(OBJDIR)/%.o) \
	$(TOP)$(OBJDIR)/test_main.o \
	$(OBJDIR)/test.o
	
REL_OBJS_LOCAL = $(OBJS:$(OBJDIR)/%.o=$(REL_OBJDIR)/%.rel)
REL_OBJS       = $(REL_OBJS_LOCAL:$(TOP)$(OBJDIR)/%.o=$(REL_OBJDIR)/%.rel)

CFLAGS += -Idata/include -Wa-Idata/include -I..

$(TOP)$(OBJDIR)/test_main.o:	$(TOP)test/framework/test_main.c
	$(CC) $(CFLAGS) -Wf-MMD -c -o $@ $<

$(OBJDIR)/%.o:	data/src/data/music/%.c
	$(CC) $(CFLAGS) -c -o $@ $<	

$(OBJDIR)/%.o:	data/src/data/sounds/%.c
	$(CC) $(CFLAGS) -c -o $@ $<	

$(OBJDIR)/%.o:	data/src/data/%.c
	$(CC) $(CFLAGS) -Wf-MMD -c -o $@ $<

$(OBJDIR)/%.o:	data/src/data/%.s
	$(CC) $(CFLAGS) -c -o $@ $<	

$(OBJDIR)/%.o:	test.c
	$(CC) $(CFLAGS) -I../framework -c -o $@ $<	

$(OBJDIR)/linkfile.lk:	$(OBJS)
$(ROM_BUILD_DIR)/%.gb:	$(OBJDIR)/linkfile.lk

.PHONY: DEMO data test recording.dem
DEMO:
	$(eval EMUFLAGS += -demoplay recording.dem)	

recording.dem:
	$(EMU) -demorec recording.dem -rom $(ROM_BUILD_DIR)/rom.gb

expected.png:
	magick capture.bmp expected.png

data:
	$(GBS_CLI) export -d project/test.gbsproj data

test: settings directories BUILD test.json
	@$(EMU) $(EMUFLAGS) -rom $(ROM_BUILD_DIR)/rom.gb
	@$(TEST_CHK) test.json $(ROM_BUILD_DIR)/rom.noi $(ROM_BUILD_DIR)/rom.sna capture.bmp
